config/routes.rb
HW4::Application.routes.draw do
  devise_for :users
  get "home/index"
  resources :users, only: [:show, :index]
  resources :quotes
  resources :books
  resources :followers, only: [:create, :destroy]
  resources :borroweds

  get "dashboard", to: "users#dash"
  

  post "search", to: "application#search"
  get "books/category/:cat", to: "books#cat_index", as: "cat_books"
  get "quotes/category/:cat", to: "quotes#cat_index", as: "cat_quotes"

  root 'home#index'

end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :user
  has_many :borrowed, :dependent => :destroy

  #validations
  validates :title, presence: true
  validates :author, presence: true
  validates :category, presence: true
  validates :body, length: {maximum: 1500}
  validates :rating, :inclusion => 1..10, presence: true
  validates :filepicker_url, presence: true
end

app/models/borrowed.rb
class Borrowed < ActiveRecord::Base
  self.table_name = 'borrowed'
  belongs_to :user
  belongs_to :book
end

app/models/follower.rb
class Follower < ActiveRecord::Base
  belongs_to :follower, :class_name=> "User"
  belongs_to :followee, :class_name=> "User"

  validates :follower_id, uniqueness: {scope: :followee_id, message: "you've already followed this person"}
end

app/models/quote.rb
class Quote < ActiveRecord::Base
  belongs_to :user
  validates :body, presence: true, length: {maximum: 300}, uniqueness: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
has_many :books, :dependent => :destroy
has_many :quotes, :dependent => :destroy
has_many :followers, foreign_key: :follower_id, :dependent => :destroy
has_many :followers, foreign_key: :followee_id, :dependent => :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
protect_from_forgery with: :exception

before_filter :configure_permitted_parameters, if: :devise_controller?

def search
	case params[:type]
		when "title","author"
			@books = Book.where(params[:type] + " LIKE ?", "%"+params[:search]+"%")
			render 'books/index'
		when "body"
			@quotes = Quote.where(params[:type] + " LIKE ?", "%"+params[:search]+"%")
			render 'quotes/index'
		when "name","email"
			@users = User.where(params[:type] + " LIKE ?", "%"+params[:search]+"%")
			render 'users/index'
		else
			render 'home/index'
		end
	end

protected

def configure_permitted_parameters
 	devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation)}
 	devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :email, :password, :password_confirmation, :current_password)}
end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	def new
		if user_signed_in?
			@book = Book.new
		else 
			redirect_to new_user_session_path
		end
	end

	def create
		@book = Book.new(book_params)
		if @book.user_id != current_user.id
			render 'new'
		else
			if @book.save
				redirect_to books_path
			else
				render 'new'
			end
		end
	end

	def index
		@books = Book.all
		@borrowed = Borrowed.new
	end

	def cat_index
		@books = Book.where(category: params[:cat])
		render 'books/index'
	end

	def show
		@book = Book.find(params[:id])
		@borrowed = Borrowed.new
	end

	def edit
		@book = Book.find(params[:id])
	end

	def update
		@book = Book.find(params[:id])
		if @book.user_id != current_user.id
			render 'edit'
		else
			if @book.update(book_params)
				redirect_to @book
			else
				render 'edit'
			end
		end
	end

	def destroy
		@book = Book.find(params[:id])
		if user_signed_in? && @book.user_id == current_user.id
			@book.destroy
			redirect_to books_path
		else
			redirect_to books_path
		end
	end

	private

	def book_params
		params.require(:book).permit(:title, :author, :filepicker_url, :body, :category, :rating, :user_id, :available)
	end

end

app/controllers/borroweds_controller.rb
class BorrowedsController < ApplicationController

def create
	@borrowed = Borrowed.new(borrowed_params)
	if @borrowed.save
		Notifications.borrow(@borrowed).deliver
		redirect_to books_path
	end
end

def destroy
		@borrowed = Borrowed.find(params[:id])
		@borrowed.destroy
		redirect_to dashboard_path
end

def borrowed_params
	params.require(:borrowed).permit(:user_id, :book_id)
end

end

app/controllers/followers_controller.rb
class FollowersController < ApplicationController

	def create
		@follower = Follower.new(follower_params)
		if @follower.save
			Notifications.followed(@follower).deliver
			redirect_to users_path
		else
			redirect_to users_path
		end
	end

	def index
		@follower = Follower.order(follower_id: :asc)
	end

	def destroy
		@follower = Follower.find(params[:id])
		@follower.destroy
		redirect_to users_path
	end

	def follower_params
		params.require(:follower).permit(:follower_id, :followee_id)
	end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
	@books = Book.order(created_at: :desc)
	if !Quote.order('RANDOM()').first.nil?
  		@randomquote = Quote.order('RANDOM()').first.body
  	end
  end
 end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
	
	def new
		if user_signed_in?
		@quote = Quote.new
		else 
			redirect_to new_user_session_path
		end
	end

	def create
		@quote = Quote.new(quote_params)
		if @quote.user_id != current_user.id
			render 'new'
		else
			if @quote.save 
				redirect_to quotes_path
			else
				render 'new'
			end
		end
	end


	def index
		@quotes = Quote.all
	end

	def cat_index
		@quotes = Quote.where(category: params[:cat])
		render 'quotes/index'
	end

	def show
		@quote = Quote.find(params[:id])
	end


	def edit
		@quote = Quote.find(params[:id])
	end

	def update
		@quote = Quote.find(params[:id])
		if @quote.user_id != current_user.id
			render 'edit'
		else
			if @quote.update(quote_params)
				redirect_to @quote
			else
				render 'edit'
			end
		end
	end

	def destroy
		@quote = Quote.find(params[:id])
	if user_signed_in? && @quote.user_id == current_user.id
		@quote.destroy
		redirect_to quotes_path
	else
		redirect_to quotes_path
	end

	end
	
 	private

	def quote_params
		params.require(:quote).permit(:body, :category, :user_id)
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
		@user=User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			redirect_to users_path
		else
			render 'new'
		end
	end

	def user_params
		params.require(:user).permit(:name, :email, :password)
	end

	def index
		@users=User.order(name: :asc)
	end
	
	def show
		@user = User.find(params[:id])
		@books = Book.where(user_id: @user.id)
		@quotes = Quote.where(user_id: @user.id)
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		if @user.update_attributes(user_params)
			redirect_to user_path(@user.id)
		else
			render 'edit'
		end
	end

	def destroy
		@user = User.find(params[:id])
		@user.destroy
		redirect_to users_path
	end

	def dash
		if user_signed_in?
			@user = current_user
			@followers = Follower.where(follower_id: current_user.id)
			@follower_id = []
			@followers.each do |follow|
				@follower_id.push(follow.followee_id)
			end
			@lent2 = Borrowed.all
			@lent_book = []
			@lent2.each do |lend|
				if !lend.book.nil?
				if lend.book.user_id == current_user.id
					@lent_book.push(lend.book)
				end
				end
			end
			@borrowed = Borrowed.where(user_id: current_user.id) 
			@books = Book.where(user_id: @follower_id).order(created_at: :desc).limit(5)
			@quotes = Quote.where(user_id: @follower_id).order(created_at: :desc).limit(5)

		else
			redirect_to users_path
		end
	end	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/borrowed_helper.rb
module BorrowedHelper
end

app/helpers/followers_helper.rb
module FollowersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<div class= "new">
<h1>Editing Book</h1>
 
<%= form_for :book, url: book_path(@book), method: :patch do |f| %>
  
    <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited
        this book from being saved:
      </h2>

      <ul>
         <% @book.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
      </ul>
  </div>
  <% end %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
 <p>
    <%= f.label :author %><br>
    <%= f.text_field :author %>
 </p>

 <p>
    <%= f.label :filepicker_url, "Upload Book Image:" %>
    <%= f.filepicker_field :filepicker_url %>
 </p>

  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
 
   <p>
    <%= f.label :category%><br>
    <%= f.select :category, options_for_select(["Action","Classic","Educational","Fantasy","Religious","Romance","Self-Help","Suspense","To Read"]) %>
  </p>

  <p>
    <%= f.label :rating %><br>
    <%= f.text_area :rating %>
  </p>

  <p>
    <%= f.label :available %><br>
    <%= f.check_box :available %>
  </p>
  
  <div class="field">
    <%= f.hidden_field :user_id, :value =>current_user.id%>
  </div>

  <p>
    <%= f.submit %>
  </p>
<% end %>
 
<%= link_to 'Back', books_path %>
</div>

app/views/books/index.html.erb
<div class="bookt">
<p>Books</p>
</div>

<ul class="categories">
	<li id= "cat"><%= link_to "Action", cat_books_path("Action")%></li>
	<li id= "cat"><%= link_to "Classic", cat_books_path("Classic")%></li>
	<li id= "cat"><%= link_to "Educational", cat_books_path("Educational")%></li>
	<li id= "cat"><%= link_to "Fantasy", cat_books_path("Fantasy")%></li>
	<li id= "cat"><%= link_to "Religious", cat_books_path("Religious")%></li>
	<li id= "cat"><%= link_to "Romance", cat_books_path("Romance")%></li>
	<li id= "cat"><%= link_to "Self-Help", cat_books_path("Self-Help")%></li>
	<li id= "cat"><%= link_to "Suspense", cat_books_path("Suspense")%></li>
	<li id= "cat"><%= link_to "To Read", cat_books_path("To Read")%></li>
</ul>

<div class = "books">
	<% @books.each do |book| %>
	<div class="bookbox">
		<p id = "title"><%= book.title%></p>
		<% if !book.filepicker_url.nil?%>
		<p id = "image"><%= filepicker_image_tag book.filepicker_url, w:180, h:260, fit: 'clip' %></p>
		<%end%>
		
		<div class="details">
		<p id = "rates">Genre: <%= book.category%> ~Rating: <%= book.rating%> </p>

		<% if user_signed_in? %>
		<% if !(Borrowed.find_by book_id: book.id) && book.available && !@borrowed.nil?%>
				<%= form_for(@borrowed) do |f| %>
					<div class = "field">
					<%= f.hidden_field :user_id, :value => current_user.id %> </div>
					<div class = "field">
					<%= f.hidden_field :book_id, :value => book.id %> </div>
					<div class= "actions">
					<%= f.submit "Borrow"%> </div>
					<%end%>
			<%else%>
				<p id="out"><%= "~Out" %></p>
		<%end%>
	<%end%>

		<p><%= book.user.name unless book.user.nil?%>		
		<%= link_to '~Show', book %>
		<% if user_signed_in? %>
		<% if book.user_id == current_user.id %>
			<%= link_to 'Edit', edit_book_path(book) %>
			<%= link_to 'Delete', book_path(book), method: :delete, data: { confirm: 'Are you sure?' } %></p>
		<%end%>
		<%end%>
		</div>

</div>

<%end%>
</div>

app/views/books/new.html.erb
<div class="new">

<%= form_for(@book) do |f| %> <!--Do I need to add a url here?-->

<% if @book.errors.any? %>
<div id="error_explanation">
	<h2><%= pluralize(@book.errors.count, "error") %> prohibited
		this book from being saved: 
	</h2>
		<ul>
			<% @book.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
			<% end %>
		</ul>
</div>
<% end %>

<div class= "field">
	<p>Title</p>
	<%=f.text_field :title%>
</div>

<div class="field">
	<p>Author</p>
	<%= f.text_field :author %>
</div>

 <div class= "field">
    <%= f.label :filepicker_url, "Upload Book Image:" %>
    <%= f.filepicker_field :filepicker_url %>
 </div>

<div class= "field">
	<p>Comments</p>
	<%= f.text_area :body %>
</div>

<div class="field">
	<p>Genre</p>
	<%= f.select :category, options_for_select(["Action","Classic","Educational","Fantasy","Religious","Romance","Self-Help","Suspense","To Read"]) %>
</div>

<div class="field">
	<p>Rating Out of 10</p>
	<%= f.text_field :rating %>
</div>

<div class="field">
	<p>Check box if you own this book:</p>
	<%= f.check_box :available%>

<div class="field">
	<%= f.hidden_field :user_id, :value => current_user.id %>
</div>

<div class= "actions">
	<%= f.submit %>
</div>

<%end%>
<%= link_to 'See All Books', books_path %>

</div>

app/views/books/show.html.erb
<div class="new">

<p>
	<strong>Title</strong>
	<%= @book.title %>
</p>

<p>
	<strong>Author</strong>
	<%= @book.author %>
</p>

<%= filepicker_image_tag @book.filepicker_url, w: 280, h: 280, fit: 'clip' %>


<p>
	<strong>Comments</strong>
	<%= @book.body %>
</p>

<p>
	<strong>Genre</strong>
	<%= @book.category %>
</p>

<p>
	<strong>Rating</strong>
	<%= @book.rating %>
</p>

<p>
	<strong>Available to Borrow</strong>
	<% if @book.available%>
		<%="I own it"%>
	<%else%>
		<%="I don't own it"%>
	<%end%>
</p>

<% if user_signed_in? %>
<p>
	<% if !(Borrowed.find_by book_id: @book.id) && !@borrowed.nil?%>
		<%= form_for(@borrowed) do |f| %>
			<div class = "field">
			<%= f.hidden_field :user_id, :value => current_user.id %> </div>
			<div class = "field">
			<%= f.hidden_field :book_id, :value => @book.id %> </div>
			<div class= "actions">
				<%= f.submit "Borrow" %> </div>
		<%end%>
	<%else%>
		<%= "This book is out" %>
	<%end%>
</p>
<%end%>

<%= link_to 'Back', books_path %> 
<% if user_signed_in? %>
<% if @book.user_id == current_user.id %>
<%= link_to 'Edit', edit_book_path(@book) %>
<%= link_to 'Delete', book_path(@book), method: :delete, data: { confirm: 'Are you sure?' } %>
<%end%>
<%end%>

</div>

app/views/home/index.html.erb
<div class = "wrap">
<div class = "rquote">
	<p><%= @randomquote %></p>
</div>
</div>

<div class="quotes">
	<%= link_to "See Quotes", quotes_path %>
</div>

<div class="book">
	<%= link_to "Books", books_path %>
</div>

<div class= "wrapper">
<div id="bookline">
	<ul>
<% @books.each do |book| %>
	<div class = "bookscroll">
		<li>
			<p> <%=filepicker_image_tag book.filepicker_url, w:160, h:160, fit: 'clip' %> </p>
			<h1><%= link_to book.title, book%></h1>
		</li>
	</div>
<%end%>
</ul>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HW4</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= filepicker_js_include_tag %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" type="text/css" href="public/bootstrap.min.css">
</head>

<body>
	<div class = "navbar">
		<ul class="nav">
			<div id="left">
				<li class = 'nav-linksearch'>
					<%= form_tag search_path, method: :post do %>
   						 <%= text_field_tag :search%>
   						 <%= select_tag(:type, options_for_select([['title', "title"],['author', "author"],['quotes',"body"],["email","email"],["name","name"]]))%>
  						 <%= submit_tag "Search", :class => "hide"%></li>
					<% end %>
				<li class = 'nav-link'><%= link_to "HOME", home_index_path %></li>
			</div>

			<div id="right">
				<% if user_signed_in? %> 
				<ul>
					<li class = 'dropdown'><a class = 'nav-link' href='#'><%=current_user.name%></a>
					<ul>
						<li class = 'nav-link'><%= link_to "DASHBOARD", dashboard_path %></li>
						<li class = 'nav-link'><%= link_to "USERS", users_path %></li> 
						<li class = 'nav-link'><%= link_to "EDIT PROFILE", edit_user_registration_path %></li>
						<li class = 'nav-link'><%=link_to('LOGOUT', destroy_user_session_path(:authenticity_token => form_authenticity_token()), :method => :delete) %></li>
					</ul>
					</li>

					<li class='nav-link'><%= link_to "+BOOKS", new_book_path %></li>
					<li class='nav-link'><%= link_to "+QUOTES", new_quote_path %></li>
				</ul>

				<% else %> 
				<li class = 'nav-link'><%=link_to('LOGIN', new_user_session_path) %></li>

				<%end%>

			</div>
		</ul>
	</div>

<p class="notice"><%=notice%></p>
<p class="alert"><%=alert%></p>

<div class="content">
<%= yield %>
</div>

</body>
</html>

app/views/notifications/borrow.html.erb
<p>
<%= @greeting %> <%= @lender %>, <%= @borrower %> has requested to borrow your book, 
<%= @book %>. You can email them at <%= @bemail %> to get in contact and exchange the book.
</p>

app/views/notifications/followed.html.erb
<h2><%= @greeting%></h2>
<p> <%= @follower%> followed you! You can check out their page <a href=<%=user_url(@id)%>>here</a></p>

app/views/quotes/delete.html.erb
<h1>Quotes#delete</h1>
<p>Find me in app/views/quotes/delete.html.erb</p>

app/views/quotes/edit.html.erb
<div class="new">
<h1>Editing Quote</h1>
 
<%= form_for :quote, url: quote_path(@quote), method: :patch do |f| %>
  <% if @quote.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@quote.errors.count, "error") %> prohibited
      this quote from being saved:</h2>
    <ul>
    <% @quote.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
 
   <p>
    <%= f.label :category %><br>
    <%= f.select :category, options_for_select(["Encouragement","Future","Humour","Inspirational","Relationships","Religious","Romantic"]) %>  
  </p>

  <div class="field">
    <%= f.hidden_field :user_id, :value =>current_user.id%>
  </div>

  <p>
    <%= f.submit %>
  </p>
<% end %>
 
<%= link_to 'Back', quotes_path %>
</div>

app/views/quotes/index.html.erb
<div class="qtitle">
<p>Quotes</p>
</div>

<ul class="categories">
	<li><%= link_to "Encouragement", cat_quotes_path("Encouragement")%></li>
	<li><%= link_to "Future", cat_quotes_path("Future")%></li>
	<li><%= link_to "Humour", cat_quotes_path("Humour")%></li>
	<li><%= link_to "Inspirational", cat_quotes_path("Inspirational")%></li>
	<li><%= link_to "Relationships", cat_quotes_path("Relationships")%></li>
	<li><%= link_to "Religious", cat_quotes_path("Religious")%></li>
	<li><%= link_to "Romantic", cat_quotes_path("Romantic")%></li>
</ul>

	<% @quotes.each do |quote| %>
	<div class="quotebox">
		<p id="qbody"><%= quote.body %></p>
		<div class="info">
		<p><%= quote.category%>~
		<%= quote.user.name unless quote.user.nil? %>
		<%= link_to '~Show', quote %>

		<% if user_signed_in? %>
		<% if quote.user_id == current_user.id %>
		<%= link_to 'Edit', edit_quote_path(quote) %>
		<%= link_to 'Delete', quote_path(quote),
                    method: :delete, data: { confirm: 'Are you sure?' } %></p>
        <%end%>
        <%end%>
    	</div>
        
	</div>

	<%end%>

app/views/quotes/show.html.erb
<div class="new">
<p>
	<strong>Quote</strong>
	<%= @quote.body %>
</p>

<p>
	<strong>Category</strong>
	<%= @quote.category %>
</p>

<%= link_to 'Back', quotes_path %> 

<% if user_signed_in? && @quote.user_id == current_user.id %>
<%= link_to 'Edit', edit_quote_path(@quote) %>
<%= link_to 'Delete', quote_path(@quote),
                    method: :delete, data: { confirm: 'Are you sure?' } %></td>
<%end%>
</div>

app/views/users/dash.html.erb
<div class="dash">
<p><%= @user.name%>'s Dashboard</p> 
</div>

<div class="selfinfo">

<div class="selfbox">
<h2> Following </h2>
	<ul>
	<% @followers.each do |follow| %>
	<li>
		<p><%= link_to follow.followee.name, follow.followee%></p>
	</li>
	<%end%>
	</ul>
</div>

<div class="selfbox">
<h2>Out</h2>
	<ul>
	<% @lent_book.each do |lent| %>
	<li>
		<p><%= lent.title%> by <%= Borrowed.where(book: lent).take!.user.name unless  Borrowed.where(book: lent).take!.user.nil?%>
		<%= link_to 'Returned', Borrowed.where(book: lent).take!,
           method: :delete, data: { confirm: 'Are you sure this book was returned?'} %></p>
	</li>
	<%end%>
	</ul>
</div>

<div class="selfbox">
<h2>Borrowing</h2>
	<ul>
	<% @borrowed.each do |borrowed| %>
	<li>
		<% if !borrowed.book.nil? %>
			<p><%= borrowed.book.title %> from <%= borrowed.book.user.name%></p>
		<%end%>
	</li>
	<%end%>
	</ul>
</div>

</div>
<div class="dashelements">
	<h2 class = "books"> Books </h2>
	<% @books.each do |book| %>
	<div class = "dashbooks">
		<p id="title"><%= link_to book.title, book_path(book.id) %></p>
		<p id="image"><%= filepicker_image_tag book.filepicker_url, w:185, h:285, fit: 'clip' %></td>
		<p id = "rates"> Genre: <%= book.category%> ~Rating: <%= book.rating%> ~Availability:
		
		<% if book.available%>
			<%="I own it"%>
			<%else%>
			<%="I don't own it"%></p>
			<%end%> 

		<p><%= link_to book.user.name, user_path(book.user_id) %>
		<%= link_to '~Show', book %>
		<% if book.user_id == current_user.id %>
			<%= link_to 'Edit', edit_book_path(book) %>
			<%= link_to 'Delete', book_path(book), method: :delete, data: { confirm: 'Are you sure?' } %></p>
		<%end%>
	</div>
	<%end%>

	<h2 class = "quotes"> Quotes </h2>
	<% @quotes.each do |quote| %>
	<div class="quotebox">
		<p id="qbody"><%= quote.body %></p>
		<div class="info">
		<p><%= quote.category%>~
		<%= quote.user.name unless quote.user.nil? %>
		<%= link_to '~Show', quote %>

		<% if user_signed_in? %>
		<% if quote.user_id == current_user.id %>
		<%= link_to 'Edit', edit_quote_path(quote) %>
		<%= link_to 'Delete', quote_path(quote),
                    method: :delete, data: { confirm: 'Are you sure?' } %></p>
        <%end%>
        <%end%>
    	</div>
        
	</div>

	<%end%>
</div>

app/views/users/show.html.erb
<p>
	<strong>Name</strong>
	<%= @user.name %>
</p>

<p>
	<strong>Email</strong>
	<%= @user.email %>
</p>

<div class="dashelements">
	<h2 class = "books"> Books </h2>

	<ul class="categories">
	<li id= "cat"><%= link_to "Action", cat_books_path("Action")%></li>
	<li id= "cat"><%= link_to "Classic", cat_books_path("Classic")%></li>
	<li id= "cat"><%= link_to "Educational", cat_books_path("Educational")%></li>
	<li id= "cat"><%= link_to "Fantasy", cat_books_path("Fantasy")%></li>
	<li id= "cat"><%= link_to "Religious", cat_books_path("Religious")%></li>
	<li id= "cat"><%= link_to "Romance", cat_books_path("Romance")%></li>
	<li id= "cat"><%= link_to "Self-Help", cat_books_path("Self-Help")%></li>
	<li id= "cat"><%= link_to "Suspense", cat_books_path("Suspense")%></li>
	<li id= "cat"><%= link_to "To Read", cat_books_path("To Read")%></li>
	</ul>

	<% @books.each do |book| %>
	<div class = "dashbooks">
		<p id="title"><%= link_to book.title, book_path(book.id) %></p>
		<p id="image"><%= filepicker_image_tag book.filepicker_url, w:185, h:285, fit: 'clip' %></td>
		<p id = "rates"> Genre: <%= book.category%> ~Rating: <%= book.rating%> ~Availability:
		
		<% if book.available%>
			<%="I own it"%>
			<%else%>
			<%="I don't own it"%></p>
			<%end%> 

		<p><%= link_to book.user.name, user_path(book.user_id) %>
		<%= link_to '~Show', book %>
		<% if book.user_id == current_user.id %>
			<%= link_to 'Edit', edit_book_path(book) %>
			<%= link_to 'Delete', book_path(book), method: :delete, data: { confirm: 'Are you sure?' } %></p>
		<%end%>
	</div>
	<%end%>

	<h2 class = "quotes"> Quotes </h2>

	<ul class="categories">
	<li><%= link_to "Encouragement", cat_quotes_path("Encouragement")%></li>
	<li><%= link_to "Future", cat_quotes_path("Future")%></li>
	<li><%= link_to "Humour", cat_quotes_path("Humour")%></li>
	<li><%= link_to "Inspirational", cat_quotes_path("Inspirational")%></li>
	<li><%= link_to "Relationships", cat_quotes_path("Relationships")%></li>
	<li><%= link_to "Religious", cat_quotes_path("Religious")%></li>
	<li><%= link_to "Romantic", cat_quotes_path("Romantic")%></li>
	</ul>
	
	<% @quotes.each do |quote| %>
	<div class="quotebox">
		<p id="qbody"><%= quote.body %></p>
		<div class="info">
		<p><%= quote.category%>~
		<%= quote.user.name unless quote.user.nil? %>
		<%= link_to '~Show', quote %>

		<% if user_signed_in? %>
		<% if quote.user_id == current_user.id %>
		<%= link_to 'Edit', edit_quote_path(quote) %>
		<%= link_to 'Delete', quote_path(quote),
                    method: :delete, data: { confirm: 'Are you sure?' } %></p>
        <%end%>
        <%end%>
    	</div>
        
	</div>

	<%end%>
</div>